! function(n) {
    function o() { e = !0, f.$wndw = n(window), f.$html = n("html"), f.$body = n("body"), n.each([t, u, r], function(n, t) { t.add = function(n) { n = n.split(" "); for (var i in n) t[n[i]] = t.mm(n[i]) } }), t.mm = function(n) { return "mm-" + n }, t.add("wrapper menu inline panel nopanel list nolist subtitle selected label spacer current highest hidden opened subopened subopen fullsubopen subclose"), t.umm = function(n) { return "mm-" == n.slice(0, 3) && (n = n.slice(3)), n }, u.mm = function(n) { return "mm-" + n }, u.add("parent"), r.mm = function(n) { return n + ".mm" }, r.add("toggle open close setSelected transitionend webkitTransitionEnd mousedown mouseup touchstart touchmove touchend scroll resize click keydown keyup"), n[i]._c = t, n[i]._d = u, n[i]._e = r, n[i].glbl = f } var i = "mmenu",
        s = "4.7.5"; if (!n[i]) { var t = {},
            u = {},
            r = {},
            e = !1,
            f = { $wndw: null, $html: null, $body: null };
        n[i] = function(t, r, u) { var e, f;
            this.$menu = t, this.opts = r, this.conf = u, this.vars = {}, "function" == typeof this.___deprecated && this.___deprecated(), this._initMenu(), this._initAnchors(), this._initEvents(), e = this.$menu.children(this.conf.panelNodetype); for (f in n[i].addons) n[i].addons[f]._add.call(this), n[i].addons[f]._add = function() {}, n[i].addons[f]._setup.call(this); return this._init(e), "function" == typeof this.___debug && this.___debug(), this }, n[i].version = s, n[i].addons = {}, n[i].uniqueId = 0, n[i].defaults = { classes: "", slidingSubmenus: !0, onClick: { setSelected: !0 } }, n[i].configuration = { panelNodetype: "ul, ol, div", transitionDuration: 400, openingInterval: 25, classNames: { panel: "Panel", selected: "Selected", label: "Label", spacer: "Spacer" } }, n[i].prototype = { _init: function(r) { r = r.not("." + t.nopanel), r = this._initPanels(r); for (var u in n[i].addons) n[i].addons[u]._init.call(this, r);
                this._update() }, _initMenu: function() { this.opts.offCanvas && this.conf.clone && (this.$menu = this.$menu.clone(!0), this.$menu.add(this.$menu.find("*")).filter("[id]").each(function() { n(this).attr("id", t.mm(n(this).attr("id"))) })), this.$menu.contents().each(function() { 3 == n(this)[0].nodeType && n(this).remove() }), this.$menu.parent().addClass(t.wrapper); var i = [t.menu];
                i.push(t.mm(this.opts.slidingSubmenus ? "horizontal" : "vertical")), this.opts.classes && i.push(this.opts.classes), this.$menu.addClass(i.join(" ")) }, _initPanels: function(i) { var c = this,
                    f, e, h, o, s; return this.__findAddBack(i, "ul, ol").not("." + t.nolist).addClass(t.list), f = this.__findAddBack(i, "." + t.list).find("> li"), this.__refactorClass(f, this.conf.classNames.selected, "selected"), this.__refactorClass(f, this.conf.classNames.label, "label"), this.__refactorClass(f, this.conf.classNames.spacer, "spacer"), f.off(r.setSelected).on(r.setSelected, function(i, r) { i.stopPropagation(), f.removeClass(t.selected), "boolean" != typeof r && (r = !0), r && n(this).addClass(t.selected) }), this.__refactorClass(this.__findAddBack(i, "." + this.conf.classNames.panel), this.conf.classNames.panel, "panel"), i.add(this.__findAddBack(i, "." + t.list).children().children().filter(this.conf.panelNodetype).not("." + t.nopanel)).addClass(t.panel), e = this.__findAddBack(i, "." + t.panel), h = n("." + t.panel, this.$menu), (e.each(function() { var t = n(this),
                        i = t.attr("id") || c.__getUniqueId();
                    t.attr("id", i) }), e.each(function() { var i = n(this),
                        o = i.is("ul, ol") ? i : i.find("ul ,ol").first(),
                        r = i.parent(),
                        f = r.children("a, span"),
                        s = r.closest("." + t.panel),
                        e;
                    r.parent().is("." + t.list) && !i.data(u.parent) && (i.data(u.parent, r), e = n('<a class="' + t.subopen + '" href="#' + i.attr("id") + '" />').insertBefore(f), f.is("a") || e.addClass(t.fullsubopen), c.opts.slidingSubmenus && o.prepend('<li class="' + t.subtitle + '"><a class="' + t.subclose + '" href="#' + s.attr("id") + '">' + f.text() + "</a></li>")) }), this.opts.slidingSubmenus) ? (o = this.__findAddBack(i, "." + t.list).find("> li." + t.selected), o.parents("li").removeClass(t.selected).end().add(o.parents("li")).each(function() { var i = n(this),
                        r = i.find("> ." + t.panel);
                    r.length && (i.parents("." + t.panel).addClass(t.subopened), r.addClass(t.opened)) }).closest("." + t.panel).addClass(t.opened).parents("." + t.panel).addClass(t.subopened)) : (o = n("li." + t.selected, h), o.parents("li").removeClass(t.selected).end().add(o.parents("li")).addClass(t.opened)), s = h.filter("." + t.opened), s.length || (s = e.first()), s.addClass(t.opened).last().addClass(t.current), this.opts.slidingSubmenus && e.not(s.last()).addClass(t.hidden).end().appendTo(this.$menu), e }, _initAnchors: function() { var u = this;
                f.$body.on(r.click, "a", function(e) { var o = n(this),
                        s = !1,
                        l = u.$menu.find(o).length,
                        a, h, c; for (a in n[i].addons)
                        if (n[i].addons[a]._clickAnchor && (s = n[i].addons[a]._clickAnchor.call(u, o, l))) break;
                    if (!s && l && (h = o.attr("href") || "", "#" == h.slice(0, 1))) try { n(h, u.$menu).is("." + t.panel) && (s = !0, n(h).trigger(u.opts.slidingSubmenus ? r.open : r.toggle)) } catch (v) {}(s && e.preventDefault(), s || !l || !o.is("." + t.list + " > li > a") || o.is('[rel="external"]') || o.is('[target="_blank"]')) || (u.__valueOrFn(u.opts.onClick.setSelected, o) && o.parent().trigger(r.setSelected), c = u.__valueOrFn(u.opts.onClick.preventDefault, o, "#" == h.slice(0, 1)), c && e.preventDefault(), u.__valueOrFn(u.opts.onClick.blockUI, o, !c) && f.$html.addClass(t.blocking), u.__valueOrFn(u.opts.onClick.close, o, c) && u.$menu.trigger(r.close)) }) }, _initEvents: function() { var i = this;
                this.$menu.on(r.toggle + " " + r.open + " " + r.close, "." + t.panel, function(n) { n.stopPropagation() }), this.opts.slidingSubmenus ? this.$menu.on(r.open, "." + t.panel, function() { return i._openSubmenuHorizontal(n(this)) }) : this.$menu.on(r.toggle, "." + t.panel, function() { var i = n(this);
                    i.trigger(i.parent().hasClass(t.opened) ? r.close : r.open) }).on(r.open, "." + t.panel, function() { n(this).parent().addClass(t.opened) }).on(r.close, "." + t.panel, function() { n(this).parent().removeClass(t.opened) }) }, _openSubmenuHorizontal: function(i) { if (i.hasClass(t.current)) return !1; var u = n("." + t.panel, this.$menu),
                    r = u.filter("." + t.current); return u.removeClass(t.highest).removeClass(t.current).not(i).not(r).addClass(t.hidden), i.hasClass(t.opened) ? r.addClass(t.highest).removeClass(t.opened).removeClass(t.subopened) : (i.addClass(t.highest), r.addClass(t.subopened)), i.removeClass(t.hidden).addClass(t.current), setTimeout(function() { i.removeClass(t.subopened).addClass(t.opened) }, this.conf.openingInterval), "open" }, _update: function(n) { if (this.updates || (this.updates = []), "function" == typeof n) this.updates.push(n);
                else
                    for (var t = 0, i = this.updates.length; i > t; t++) this.updates[t].call(this, n) }, __valueOrFn: function(n, t, i) { return "function" == typeof n ? n.call(t[0]) : "undefined" == typeof n && "undefined" != typeof i ? i : n }, __refactorClass: function(n, i, r) { return n.filter("." + i).removeClass(i).addClass(t[r]) }, __findAddBack: function(n, t) { return n.find(t).add(n.filter(t)) }, __transitionend: function(n, t, i) { var f = !1,
                    u = function() { f || t.call(n[0]), f = !0 };
                n.one(r.transitionend, u), n.one(r.webkitTransitionEnd, u), setTimeout(u, 1.1 * i) }, __getUniqueId: function() { return t.mm(n[i].uniqueId++) } }, n.fn[i] = function(t, r) { return e || o(), t = n.extend(!0, {}, n[i].defaults, t), r = n.extend(!0, {}, n[i].configuration, r), this.each(function() { var u = n(this);
                u.data(i) || u.data(i, new n[i](u, t, r)) }) }, n[i].support = { touch: "ontouchstart" in window || navigator.msMaxTouchPoints } } }(jQuery), ! function(n) { var f = "mmenu",
        u = "offCanvas",
        t, e, r, i;
    n[f].addons[u] = { _init: function() {}, _setup: function() { var o; if (this.opts[u]) { var s = this,
                    e = this.opts[u],
                    f = this.conf[u]; "string" != typeof f.pageSelector && (f.pageSelector = "> " + f.pageNodetype), i.$allMenus = (i.$allMenus || n()).add(this.$menu), this.vars.opened = !1, o = [t.offcanvas], "left" != e.position && o.push(t.mm(e.position)), "back" != e.zposition && o.push(t.mm(e.zposition)), this.$menu.addClass(o.join(" ")).parent().removeClass(t.wrapper), this.setPage(i.$page), this[u + "_initBlocker"](), this[u + "_initWindow"](), this.$menu.on(r.open + " " + r.opening + " " + r.opened + " " + r.close + " " + r.closing + " " + r.closed + " " + r.setPage, function(n) { n.stopPropagation() }).on(r.open + " " + r.close + " " + r.setPage, function(n) { s[n.type]() }), this.$menu[f.menuInjectMethod + "To"](f.menuWrapperSelector) } }, _add: function() { t = n[f]._c, e = n[f]._d, r = n[f]._e, t.add("offcanvas slideout modal background opening blocker page"), e.add("style"), r.add("opening opened closing closed setPage"), i = n[f].glbl }, _clickAnchor: function(n) { var r; return this.opts[u] ? (r = this.$menu.attr("id"), r && r.length && (this.conf.clone && (r = t.umm(r)), n.is('[href="#' + r + '"]'))) ? (this.open(), !0) : i.$page ? (r = i.$page.attr("id"), r && r.length && n.is('[href="#' + r + '"]') ? (this.close(), !0) : !1) : void 0 : !1 } }, n[f].defaults[u] = { position: "left", zposition: "back", modal: !1, moveBackground: !0 }, n[f].configuration[u] = { pageNodetype: "div", pageSelector: null, menuWrapperSelector: "body", menuInjectMethod: "prepend" }, n[f].prototype.open = function() { if (this.vars.opened) return !1; var n = this; return this._openSetup(), setTimeout(function() { n._openFinish() }, this.conf.openingInterval), "open" }, n[f].prototype._openSetup = function() { var f = this,
            n;
        i.$allMenus.not(this.$menu).trigger(r.close), i.$page.data(e.style, i.$page.attr("style") || ""), i.$wndw.trigger(r.resize, [!0]), n = [t.opened], this.opts[u].modal && n.push(t.modal), this.opts[u].moveBackground && n.push(t.background), "left" != this.opts[u].position && n.push(t.mm(this.opts[u].position)), "back" != this.opts[u].zposition && n.push(t.mm(this.opts[u].zposition)), this.opts.classes && n.push(this.opts.classes), i.$html.addClass(n.join(" ")), setTimeout(function() { f.vars.opened = !0 }, this.conf.openingInterval), this.$menu.addClass(t.current + " " + t.opened) }, n[f].prototype._openFinish = function() { var n = this;
        this.__transitionend(i.$page, function() { n.$menu.trigger(r.opened) }, this.conf.transitionDuration), i.$html.addClass(t.opening), this.$menu.trigger(r.opening) }, n[f].prototype.close = function() { if (!this.vars.opened) return !1; var n = this; return this.__transitionend(i.$page, function() { n.$menu.removeClass(t.current).removeClass(t.opened), i.$html.removeClass(t.opened).removeClass(t.modal).removeClass(t.background).removeClass(t.mm(n.opts[u].position)).removeClass(t.mm(n.opts[u].zposition)), n.opts.classes && i.$html.removeClass(n.opts.classes), i.$page.attr("style", i.$page.data(e.style)), n.vars.opened = !1, n.$menu.trigger(r.closed) }, this.conf.transitionDuration), i.$html.removeClass(t.opening), this.$menu.trigger(r.closing), "close" }, n[f].prototype.setPage = function(r) { r || (r = n(this.conf[u].pageSelector, i.$body), r.length > 1 && (r = r.wrapAll("<" + this.conf[u].pageNodetype + " />").parent())), r.addClass(t.page + " " + t.slideout), i.$page = r }, n[f].prototype[u + "_initWindow"] = function() { i.$wndw.on(r.keydown, function(n) { if (i.$html.hasClass(t.opened) && 9 == n.keyCode) return n.preventDefault(), !1 }); var e = 0;
        i.$wndw.on(r.resize, function(n, r) { if (r || i.$html.hasClass(t.opened)) { var u = i.$wndw.height();
                (r || u != e) && (e = u, i.$page.css("minHeight", u)) } }), n[f].prototype[u + "_initWindow"] = function() {} }, n[f].prototype[u + "_initBlocker"] = function() { var e = n('<div id="' + t.blocker + '" class="' + t.slideout + '" />').appendTo(i.$body);
        e.on(r.touchstart, function(n) { n.preventDefault(), n.stopPropagation(), e.trigger(r.mousedown) }).on(r.mousedown, function(n) { n.preventDefault(), i.$html.hasClass(t.modal) || i.$allMenus.trigger(r.close) }), n[f].prototype[u + "_initBlocker"] = function() {} } }(jQuery);